import { css } from 'lit';

export default css`
  /* autogenerated by scrips/make-dt-css.js */

  /* ------------------- ./src/tokens/css/000-dt-global-klik-colors.css ----------------------*/
  /*
* Global DT Color Primitives
*/
  :root {
    /* slate */
    --dt-global-klik-color-slate-10: 252 252 252;
    --dt-global-klik-color-slate-30: 248 248 248;
    --dt-global-klik-color-slate-50: 241 241 241;
    --dt-global-klik-color-slate-100: 227 227 225;
    --dt-global-klik-color-slate-200: 207 207 204;
    --dt-global-klik-color-slate-300: 178 178 176;
    --dt-global-klik-color-slate-400: 150 150 148;
    --dt-global-klik-color-slate-500: 118 118 116;
    --dt-global-klik-color-slate-600: 97 97 95;
    --dt-global-klik-color-slate-700: 77 77 75;
    --dt-global-klik-color-slate-800: 59 59 57;
    --dt-global-klik-color-slate-900: 41 41 40;

    /* turquoise */
    --dt-global-klik-color-turquoise-10: 250 253 253;
    --dt-global-klik-color-turquoise-30: 242 251 252;
    --dt-global-klik-color-turquoise-50: 223 242 245;
    --dt-global-klik-color-turquoise-100: 194 236 242;
    --dt-global-klik-color-turquoise-200: 139 220 232;
    --dt-global-klik-color-turquoise-300: 81 196 214;
    --dt-global-klik-color-turquoise-400: 31 163 184;
    --dt-global-klik-color-turquoise-500: 6 130 148;
    --dt-global-klik-color-turquoise-600: 1 105 120;
    --dt-global-klik-color-turquoise-700: 1 82 94;
    --dt-global-klik-color-turquoise-800: 4 63 71;
    --dt-global-klik-color-turquoise-900: 6 45 51;

    /* teal */
    --dt-global-klik-color-teal-10: 250 252 252;
    --dt-global-klik-color-teal-30: 245 249 250;
    --dt-global-klik-color-teal-50: 233 242 245;
    --dt-global-klik-color-teal-100: 211 231 237;
    --dt-global-klik-color-teal-200: 177 211 222;
    --dt-global-klik-color-teal-300: 141 186 201;
    --dt-global-klik-color-teal-400: 97 152 171;
    --dt-global-klik-color-teal-500: 70 123 140;
    --dt-global-klik-color-teal-600: 55 104 120;
    --dt-global-klik-color-teal-700: 41 79 92;
    --dt-global-klik-color-teal-800: 32 60 69;
    --dt-global-klik-color-teal-900: 21 36 41;

    /* light-blue */
    --dt-global-klik-color-light-blue-10: 249 251 252;
    --dt-global-klik-color-light-blue-30: 245 248 250;
    --dt-global-klik-color-light-blue-50: 232 242 250;
    --dt-global-klik-color-light-blue-100: 202 229 250;
    --dt-global-klik-color-light-blue-200: 166 211 247;
    --dt-global-klik-color-light-blue-300: 121 188 242;
    --dt-global-klik-color-light-blue-400: 69 153 222;
    --dt-global-klik-color-light-blue-500: 36 123 191;
    --dt-global-klik-color-light-blue-600: 23 102 166;
    --dt-global-klik-color-light-blue-700: 15 83 138;
    --dt-global-klik-color-light-blue-800: 12 65 107;
    --dt-global-klik-color-light-blue-900: 10 44 71;

    /* dark-blue */
    --dt-global-klik-color-dark-blue-10: 250 251 252;
    --dt-global-klik-color-dark-blue-30: 242 246 252;
    --dt-global-klik-color-dark-blue-50: 232 240 252;
    --dt-global-klik-color-dark-blue-100: 210 225 252;
    --dt-global-klik-color-dark-blue-200: 177 204 250;
    --dt-global-klik-color-dark-blue-300: 138 177 242;
    --dt-global-klik-color-dark-blue-400: 95 145 232;
    --dt-global-klik-color-dark-blue-500: 52 110 209;
    --dt-global-klik-color-dark-blue-600: 25 81 178;
    --dt-global-klik-color-dark-blue-700: 12 57 135;
    --dt-global-klik-color-dark-blue-800: 11 47 110;
    --dt-global-klik-color-dark-blue-900: 11 37 82;

    /* purple */
    --dt-global-klik-color-purple-10: 251 250 252;
    --dt-global-klik-color-purple-30: 248 245 252;
    --dt-global-klik-color-purple-50: 243 237 252;
    --dt-global-klik-color-purple-100: 232 220 250;
    --dt-global-klik-color-purple-200: 212 191 245;
    --dt-global-klik-color-purple-300: 191 162 235;
    --dt-global-klik-color-purple-400: 162 126 217;
    --dt-global-klik-color-purple-500: 138 98 196;
    --dt-global-klik-color-purple-600: 115 76 173;
    --dt-global-klik-color-purple-700: 91 58 140;
    --dt-global-klik-color-purple-800: 69 43 107;
    --dt-global-klik-color-purple-900: 46 32 66;

    /* magenta */
    --dt-global-klik-color-magenta-10: 252 250 251;
    --dt-global-klik-color-magenta-30: 252 245 248;
    --dt-global-klik-color-magenta-50: 252 235 243;
    --dt-global-klik-color-magenta-100: 252 212 231;
    --dt-global-klik-color-magenta-200: 250 182 214;
    --dt-global-klik-color-magenta-300: 242 148 192;
    --dt-global-klik-color-magenta-400: 229 103 162;
    --dt-global-klik-color-magenta-500: 207 62 129;
    --dt-global-klik-color-magenta-600: 178 37 103;
    --dt-global-klik-color-magenta-700: 140 22 77;
    --dt-global-klik-color-magenta-800: 97 19 56;
    --dt-global-klik-color-magenta-900: 64 22 42;

    /* copper */
    --dt-global-klik-color-copper-10: 255 253 250;
    --dt-global-klik-color-copper-30: 252 247 240;
    --dt-global-klik-color-copper-50: 250 239 225;
    --dt-global-klik-color-copper-100: 251 220 183;
    --dt-global-klik-color-copper-200: 243 196 139;
    --dt-global-klik-color-copper-300: 227 166 91;
    --dt-global-klik-color-copper-400: 204 138 55;
    --dt-global-klik-color-copper-500: 163 104 31;
    --dt-global-klik-color-copper-600: 133 83 21;
    --dt-global-klik-color-copper-700: 101 65 19;
    --dt-global-klik-color-copper-800: 74 50 20;
    --dt-global-klik-color-copper-900: 51 37 20;

    /* information */
    --dt-global-klik-color-information-50: 230 245 252;
    --dt-global-klik-color-information-100: 197 234 252;
    --dt-global-klik-color-information-400: 23 159 227;
    --dt-global-klik-color-information-500: 0 124 186;
    --dt-global-klik-color-information-600: 5 104 153;

    /* success */
    --dt-global-klik-color-success-50: 232 247 230;
    --dt-global-klik-color-success-100: 211 247 208;
    --dt-global-klik-color-success-400: 28 178 12;
    --dt-global-klik-color-success-500: 16 138 6;
    --dt-global-klik-color-success-600: 17 110 9;

    /* warning */
    --dt-global-klik-color-warning-50: 252 242 219;
    --dt-global-klik-color-warning-100: 252 233 192;
    --dt-global-klik-color-warning-400: 242 167 5;
    --dt-global-klik-color-warning-500: 158 108 0;
    --dt-global-klik-color-warning-600: 128 87 0;

    /* error */
    --dt-global-klik-color-error-50: 255 242 242;
    --dt-global-klik-color-error-100: 255 222 222;
    --dt-global-klik-color-error-400: 245 91 91;
    --dt-global-klik-color-error-500: 219 31 31;
    --dt-global-klik-color-error-600: 178 7 7;

    --dt-global-klik-color-black: 10 10 10;
    --dt-global-klik-color-white: 255 255 255;
  }

  /* ------------------- ./src/tokens/css/000-dt-global-klik-ui.css ----------------------*/
  /**
 * Manually copied style keys from klik-ui
 * TODO: Should come from Style-Dictionary
 *
 * Left-hand keys  : --dt-global-klikui-*
 * Right-hand keys : hardcoded value
 *
 */
  :root {
    /* Shadows */
    --dt-global-klikui-shadows-button: 0px 1px 0px rgba(0, 0, 0, 0.1), inset 0px -1px 0px rgba(0, 0, 0, 0.15);
    --dt-global-klikui-shadows--1: inset 0px 2px 0px rgba(0, 0, 0, 0.1);

    /* Borders */
    --dt-global-klikui-border-none: 0;
    --dt-global-klikui-border-1px: 1px solid;
    --dt-global-klikui-border-2px: 2px solid;
    --dt-global-klikui-border-4px: 4px solid;
    --dt-global-klikui-border-8px: 8px solid;

    /* Radius */
    --dt-global-klikui-radii-none: 0;
    --dt-global-klikui-radii-sm: 0.125rem; /* 2px */
    --dt-global-klikui-radii-base: 0.25rem; /* 4px */
    --dt-global-klikui-radii-md: 0.375rem; /* 6px */
    --dt-global-klikui-radii-lg: 0.5rem; /* 8px */
    --dt-global-klikui-radii-xl: 0.75rem; /* 12px */
    --dt-global-klikui-radii-2xl: 1rem; /* 16px */
    --dt-global-klikui-radii-3xl: 1.5rem; /* 24px */
    --dt-global-klikui-radii-full: 9999px;

    /* Sizes */
    --dt-global-klikui-size-input-small: 2rem;
    --dt-global-klikui-size-input-medium: 3rem;
    --dt-global-klikui-size-input-large: 4rem;

    /* Typo */
    --dt-global-klikui-fontfamily-body: 'Cera Pro';
    --dt-global-klikui-fontfamily-heading: 'Cera Pro';
    --dt-global-klikui-fontfamily-mono: 'SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace';

    --dt-global-klikui-fontweight-hairline: 100;
    --dt-global-klikui-fontweight-thin: 200;
    --dt-global-klikui-fontweight-light: 300;
    --dt-global-klikui-fontweight-normal: 400;
    --dt-global-klikui-fontweight-medium: 500;
    --dt-global-klikui-fontweight-semibold: 600;
    --dt-global-klikui-fontweight-bold: 700;
    --dt-global-klikui-fontweight-extrabold: 800;
    --dt-global-klikui-fontweight-black: 900;

    --dt-global-klikui-fontsize-xs: 0.75rem;
    --dt-global-klikui-fontsize-sm: 0.875rem;
    --dt-global-klikui-fontsize-md: 1rem;
    --dt-global-klikui-fontsize-lg: 1.125rem;
    --dt-global-klikui-fontsize-xl: 1.25rem;
    --dt-global-klikui-fontsize-2xl: 1.5625rem;
    --dt-global-klikui-fontsize-3xl: 1.9375rem;
    --dt-global-klikui-fontsize-4xl: 2.4375rem;
    --dt-global-klikui-fontsize-5xl: 3.0625rem;
    --dt-global-klikui-fontsize-6xl: 3.8125rem;
    --dt-global-klikui-fontsize-7xl: 4.75rem;
    --dt-global-klikui-fontsize-8xl: 5.9375rem;

    --dt-global-klikui-lineheight-xs: 1rem;
    --dt-global-klikui-lineheight-sm: 1.25rem;
    --dt-global-klikui-lineheight-md: 1.5rem;
    --dt-global-klikui-lineheight-lg: 1.75rem;
    --dt-global-klikui-lineheight-xl: 2rem;
    --dt-global-klikui-lineheight-2xl: 2.25rem;
    --dt-global-klikui-lineheight-3xl: 2.5rem;
    --dt-global-klikui-lineheight-4xl: 3rem;
    --dt-global-klikui-lineheight-5xl: 3.75rem;
    --dt-global-klikui-lineheight-6xl: 4.5rem;
    --dt-global-klikui-lineheight-7xl: 5.5rem;
    --dt-global-klikui-lineheight-8xl: 6.75rem;
  }

  /* ------------------- ./src/tokens/css/000-dtx-defaults-light.css ----------------------*/
  /**
 * A complete set of defaults for all exposed component keys
 *
 * To redefine a value, add the key(s) to dtx-map (and ideally dtx-alias)
 */
  :root,
  :host,
  .klik-theme-light {
    /*
   * Border radii
   */

    --klik-border-radius-small: 0.125rem; /* 2px */
    --klik-border-radius-medium: 0.25rem; /* 4px */
    --klik-border-radius-large: 0.5rem; /* 8px */
    --klik-border-radius-x-large: 1rem; /* 16px */

    --klik-border-radius-circle: 50%;
    --klik-border-radius-pill: 9999px;

    /*
    * Elevations
    */

    --klik-shadow-x-small: 0 1px 2px rgb(var(--klik-color-neutral-500) / 6%);
    --klik-shadow-small: 0 1px 2px rgb(var(--klik-color-neutral-500) / 12%);
    --klik-shadow-medium: 0 2px 4px rgb(var(--klik-color-neutral-500) / 12%);
    --klik-shadow-large: 0 2px 8px rgb(var(--klik-color-neutral-500) / 12%);
    --klik-shadow-x-large: 0 4px 16px rgb(var(--klik-color-neutral-500) / 12%);

    /*
    * Surfaces
    */

    --klik-surface-base: var(--klik-color-neutral-0);
    --klik-surface-base-alt: var(--klik-color-neutral-0);

    /*
    * Spacings
    */

    --klik-spacing-3x-small: 0.125rem; /* 2px */
    --klik-spacing-2x-small: 0.25rem; /* 4px */
    --klik-spacing-x-small: 0.5rem; /* 8px */
    --klik-spacing-small: 0.75rem; /* 12px */
    --klik-spacing-medium: 1rem; /* 16px */
    --klik-spacing-large: 1.25rem; /* 20px */
    --klik-spacing-x-large: 1.75rem; /* 28px */
    --klik-spacing-2x-large: 2.25rem; /* 36px */
    --klik-spacing-3x-large: 3rem; /* 48px */
    --klik-spacing-4x-large: 4.5rem; /* 72px */

    /*
    * Transitions
    */

    --klik-transition-x-slow: 1000ms;
    --klik-transition-slow: 500ms;
    --klik-transition-medium: 250ms;
    --klik-transition-fast: 150ms;
    --klik-transition-x-fast: 50ms;

    /*
    * Typography
    */

    /* Fonts */
    --klik-font-mono: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
    --klik-font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif,
      'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
    --klik-font-serif: Georgia, 'Times New Roman', serif;

    /* Font sizes */
    --klik-font-size-2x-small: 0.625rem; /* 10px */
    --klik-font-size-x-small: 0.75rem; /* 12px */
    --klik-font-size-small: 0.875rem; /* 14px */
    --klik-font-size-medium: 1rem; /* 16px */
    --klik-font-size-large: 1.25rem; /* 20px */
    --klik-font-size-x-large: 1.5rem; /* 24px */
    --klik-font-size-2x-large: 2.25rem; /* 36px */
    --klik-font-size-3x-large: 3rem; /* 48px */
    --klik-font-size-4x-large: 4.5rem; /* 72px */

    /* Font weights */
    --klik-font-weight-light: 300;
    --klik-font-weight-normal: 400;
    --klik-font-weight-semibold: 500;
    --klik-font-weight-bold: 700;

    /* Letter spacings */
    --klik-letter-spacing-denser: -0.03em;
    --klik-letter-spacing-dense: -0.015em;
    --klik-letter-spacing-normal: normal;
    --klik-letter-spacing-loose: 0.075em;
    --klik-letter-spacing-looser: 0.15em;

    /* Line heights */
    --klik-line-height-denser: 1;
    --klik-line-height-dense: 1.4;
    --klik-line-height-normal: 1.8;
    --klik-line-height-loose: 2.2;
    --klik-line-height-looser: 2.6;

    /*
    * Forms
    */

    /* Focus rings */
    --klik-focus-ring-color: var(--klik-color-primary-500);
    --klik-focus-ring-width: 3px;
    --klik-focus-ring-alpha: 40%;
    --klik-focus-ring: 0 0 0 var(--klik-focus-ring-width)
      rgb(var(--klik-focus-ring-color) / var(--klik-focus-ring-alpha));

    /* Buttons */
    --klik-button-font-size-small: var(--klik-font-size-x-small);
    --klik-button-font-size-medium: var(--klik-font-size-small);
    --klik-button-font-size-large: var(--klik-font-size-medium);

    /* Inputs */
    --klik-input-height-small: 1.875rem; /* 30px */
    --klik-input-height-medium: 2.5rem; /* 40px */
    --klik-input-height-large: 3.125rem; /* 50px */

    --klik-input-background-color: var(--klik-color-neutral-0);
    --klik-input-background-color-hover: var(--klik-input-background-color);
    --klik-input-background-color-focus: var(--klik-input-background-color);
    --klik-input-background-color-disabled: var(--klik-color-neutral-100);
    --klik-input-border-color: var(--klik-color-neutral-300);
    --klik-input-border-color-hover: var(--klik-color-neutral-400);
    --klik-input-border-color-focus: var(--klik-color-primary-500);
    --klik-input-border-color-disabled: var(--klik-color-neutral-300);
    --klik-input-border-width: 1px;

    --klik-input-border-radius-small: var(--klik-border-radius-medium);
    --klik-input-border-radius-medium: var(--klik-border-radius-medium);
    --klik-input-border-radius-large: var(--klik-border-radius-medium);

    --klik-input-font-family: var(--klik-font-sans);
    --klik-input-font-weight: var(--klik-font-weight-normal);
    --klik-input-font-size-small: var(--klik-font-size-small);
    --klik-input-font-size-medium: var(--klik-font-size-medium);
    --klik-input-font-size-large: var(--klik-font-size-large);
    --klik-input-letter-spacing: var(--klik-letter-spacing-normal);

    --klik-input-color: var(--klik-color-neutral-700);
    --klik-input-color-hover: var(--klik-color-neutral-700);
    --klik-input-color-focus: var(--klik-color-neutral-700);
    --klik-input-color-disabled: var(--klik-color-neutral-900);
    --klik-input-icon-color: var(--klik-color-neutral-500);
    --klik-input-icon-color-hover: var(--klik-color-neutral-600);
    --klik-input-icon-color-focus: var(--klik-color-neutral-600);
    --klik-input-placeholder-color: var(--klik-color-neutral-500);
    --klik-input-placeholder-color-disabled: var(--klik-color-neutral-600);
    --klik-input-spacing-small: var(--klik-spacing-small);
    --klik-input-spacing-medium: var(--klik-spacing-medium);
    --klik-input-spacing-large: var(--klik-spacing-large);

    --klik-input-filled-background-color: var(--klik-color-neutral-100);
    --klik-input-filled-background-color-hover: var(--klik-color-neutral-100);
    --klik-input-filled-background-color-focus: var(--klik-color-neutral-0);
    --klik-input-filled-background-color-disabled: var(--klik-color-neutral-100);
    --klik-input-filled-color: var(--klik-color-neutral-800);
    --klik-input-filled-color-hover: var(--klik-color-neutral-800);
    --klik-input-filled-color-focus: var(--klik-color-neutral-700);
    --klik-input-filled-color-disabled: var(--klik-color-neutral-800);

    /* Labels */
    --klik-input-label-font-size-small: var(--klik-font-size-small);
    --klik-input-label-font-size-medium: var(--klik-font-size-medium);
    --klik-input-label-font-size-large: var(--klik-font-size-large);

    --klik-input-label-color: inherit;

    /* Help text */
    --klik-input-help-text-font-size-small: var(--klik-font-size-x-small);
    --klik-input-help-text-font-size-medium: var(--klik-font-size-small);
    --klik-input-help-text-font-size-large: var(--klik-font-size-medium);

    --klik-input-help-text-color: var(--klik-color-neutral-500);

    /* Toggles (checkboxes, radios, switches) */
    --klik-toggle-size: 1rem;

    /*
    * Overlays
    */

    --klik-overlay-background-color: var(--klik-color-blue-gray-500);
    --klik-overlay-opacity: 33%;

    /*
    * Panels
    */

    --klik-panel-background-color: var(--klik-surface-base-alt);
    --klik-panel-border-color: var(--klik-color-neutral-200);
    --klik-panel-border-width: 1px;

    /*
    * Tooltips
    */

    --klik-tooltip-border-radius: var(--klik-border-radius-medium);
    --klik-tooltip-background-color: var(--klik-color-neutral-800);
    --klik-tooltip-color: var(--klik-color-neutral-0);
    --klik-tooltip-font-family: var(--klik-font-sans);
    --klik-tooltip-font-weight: var(--klik-font-weight-normal);
    --klik-tooltip-font-size: var(--klik-font-size-small);
    --klik-tooltip-line-height: var(--klik-line-height-dense);
    --klik-tooltip-padding: var(--klik-spacing-2x-small) var(--klik-spacing-x-small);
    --klik-tooltip-arrow-size: 5px;
    --klik-tooltip-arrow-start-end-offset: 8px;

    /*
    * Z-indexes
    */

    --klik-z-index-drawer: 700;
    --klik-z-index-dialog: 800;
    --klik-z-index-dropdown: 900;
    --klik-z-index-toast: 950;
    --klik-z-index-tooltip: 1000;

    /**
    * Fallback Colors
    */

    /* Neutral */
    --klik-color-neutral-0: 255 255 255;
    --klik-color-neutral-50: 250 250 250;
    --klik-color-neutral-100: 244 244 245;
    --klik-color-neutral-200: 228 228 231;
    --klik-color-neutral-300: 212 212 216;
    --klik-color-neutral-400: 161 161 170;
    --klik-color-neutral-500: 113 113 122;
    --klik-color-neutral-600: 82 82 91;
    --klik-color-neutral-700: 63 63 70;
    --klik-color-neutral-800: 39 39 42;
    --klik-color-neutral-900: 24 24 27;
    --klik-color-neutral-950: 19 19 22;
    --klik-color-neutral-1000: 0 0 0;

    /* Success */
    --klik-color-success-50: 240 253 244;
    --klik-color-success-100: 220 252 231;
    --klik-color-success-200: 187 247 208;
    --klik-color-success-300: 134 239 172;
    --klik-color-success-400: 74 222 128;
    --klik-color-success-500: 34 197 94;
    --klik-color-success-600: 22 163 74;
    --klik-color-success-700: 21 128 61;
    --klik-color-success-800: 22 101 52;
    --klik-color-success-900: 20 83 45;
    --klik-color-success-950: 12 49 27;

    /* Warning */
    --klik-color-warning-50: 255 251 235;
    --klik-color-warning-100: 254 243 199;
    --klik-color-warning-200: 253 230 138;
    --klik-color-warning-300: 252 211 77;
    --klik-color-warning-400: 251 191 36;
    --klik-color-warning-500: 245 158 11;
    --klik-color-warning-600: 217 119 6;
    --klik-color-warning-700: 180 83 9;
    --klik-color-warning-800: 146 64 14;
    --klik-color-warning-900: 120 53 15;
    --klik-color-warning-950: 74 35 11;

    /* Danger */
    --klik-color-danger-50: 254 242 242;
    --klik-color-danger-100: 254 226 226;
    --klik-color-danger-200: 254 202 202;
    --klik-color-danger-300: 252 165 165;
    --klik-color-danger-400: 248 113 113;
    --klik-color-danger-500: 239 68 68;
    --klik-color-danger-600: 220 38 38;
    --klik-color-danger-700: 185 28 28;
    --klik-color-danger-800: 153 27 27;
    --klik-color-danger-900: 127 29 29;
    --klik-color-danger-950: 80 20 20;

    /* js exts */
    --klik-color-primary-interaction: var(klik-color-neutral-500);
    --klik-color-primary-interaction-hover: var(klik-color-neutral-600);
    --klik-color-primary-interaction-text: var(klik-color-neutral-0);

    --klik-button-shadow: 'none';
  }

  /* ------------------- ./src/tokens/css/100-setup.css ----------------------*/
  /**
 * Document-wide setup
 */

  /* * {
  font-family: var(--klik-font-sans);
} */

  :root {
    font-size: 16px;
    font-feature-settings: 'kern';

    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }

  /* ------------------- ./src/tokens/css/200-dtx-alias.css ----------------------*/
  /**
 * Map Globals to Aliasas
 *
 * Left-hand keys  : --dt-alias-*
 * Right-hand keys : --dt-global-* or hardcoded value
 *
 * */
  :root {
    --dt-alias-fontfamily-sans: 'Cera Pro';
    --dt-alias-fontfamily-input: 'Cera Pro';

    --dt-alias-color-primary-interaction: var(--dt-global-klik-color-light-blue-500);
    --dt-alias-color-primary-interaction-hover: var(--dt-global-klik-color-light-blue-600);
    --dt-alias-color-primary-interaction-text: var(--dt-global-klik-color-white);
  }

  /* ------------------- ./src/tokens/css/400-dtx-map.css ----------------------*/
  /**
 * Map Aliases to Component Styles
 *
 * Left-hand keys  : --klik-*
 * Right-hand keys : --dt-alias-* (or --dt-global-* if used without alias layer)
 *
 * See dtx-defaults-* for keys to redefine/link
 */
  :root {
    /* typo */
    --klik-font-sans: var(--dt-alias-fontfamily-sans);
    --klik-input-font-family: var(--dt-alias-fontfamily-input);

    /* Font sizes */
    --klik-font-size-2x-small: 0.625rem; /* 10px */
    --klik-font-size-x-small: var(--dt-global-klikui-fontsize-xs);
    --klik-font-size-small: var(--dt-global-klikui-fontsize-sm);
    --klik-font-size-medium: var(--dt-global-klikui-fontsize-md);
    --klik-font-size-large: var(--dt-global-klikui-fontsize-lg);
    --klik-font-size-x-large: var(--dt-global-klikui-fontsize-xl);
    --klik-font-size-2x-large: var(--dt-global-klikui-fontsize-2xl);
    --klik-font-size-3x-large: var(--dt-global-klikui-fontsize-3xl);
    --klik-font-size-4x-large: var(--dt-global-klikui-fontsize-4xl);

    /* Font weights */
    --klik-font-weight-light: var(--dt-global-klikui-fontweight-light);
    --klik-font-weight-normal: var(--dt-global-klikui-fontweight-normal);
    --klik-font-weight-medium: var(--dt-global-klikui-fontweight-medium);
    --klik-font-weight-semibold: var(--dt-global-klikui-fontweight-semibold);
    --klik-font-weight-bold: var(--dt-global-klikui-fontweight-bold);

    /* Line heights */
    --klik-line-height-denser: 1;
    --klik-line-height-dense: 1.4;
    --klik-line-height-normal: 1.8;
    --klik-line-height-loose: 2.2;
    --klik-line-height-looser: 2.6;

    /* primary interaction */
    --klik-color-primary-interaction: var(--dt-alias-color-primary-interaction);
    --klik-color-primary-interaction-hover: var(--dt-alias-color-primary-interaction-hover);
    --klik-color-primary-interaction-text: var(--dt-alias-color-primary-interaction-text);

    /* buttons */
    --klik-button-shadow: var(--dt-global-klikui-shadows-button);
    --klik-button-outline-background-hover: var(--dt-global-klik-color-slate-50);

    --klik-button-font-size-small: var(--dt-global-klikui-fontsize-medium);
    --klik-button-font-size-medium: var(--dt-global-klikui-fontsize-medium);
    --klik-button-font-size-large: var(--dt-global-klikui-fontsize-xl);

    /* radii */
    --klik-border-radius-small: var(--dt-global-klikui-radii-sm);
    --klik-border-radius-medium: var(--dt-global-klikui-radii-base);
    --klik-border-radius-large: var(--dt-global-klikui-radii-medium);
    --klik-border-radius-x-large: var(--dt-global-klikui-radii-large);

    /* input */
    --klik-input-border-width: var(--dt-global-klikui-border-2px);

    --klik-input-height-small: var(--dt-global-klikui-size-input-small);
    --klik-input-height-medium: var(--dt-global-klikui-size-input-medium);
    --klik-input-height-large: var(--dt-global-klikui-size-input-large);

    --klik-input-font-weight-medium: var(--dt-global-klikui-fontweight-medium);

    --klik-input-font-size-small: var(--dt-global-klikui-fontsize-medium);
    --klik-input-font-size-medium: var(--dt-global-klikui-fontsize-lg);
    --klik-input-font-size-large: var(--dt-global-klikui-fontsize-xl);

    --klik-button-icon-size-small: 0.875rem; /* */
    --klik-button-icon-size-medium: 1rem;
    --klik-button-icon-size-large: 1.625rem; /* */
  }

  /* ------------------- ./src/tokens/css/900-fonts-cerapro.css ----------------------*/
  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: 300;
    src: url('../assets/fonts/cera-pro/CeraPro-Light.eot');
    src: local('Cera Pro Light'), local('CeraPro-Light'),
      url('../assets/fonts/cera-pro/CeraPro-Light.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Light.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Light.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Light.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: 500;
    src: url('../assets/fonts/cera-pro/CeraPro-MediumItalic.eot');
    src: local('Cera Pro Medium Italic'), local('CeraPro-MediumItalic'),
      url('../assets/fonts/cera-pro/CeraPro-MediumItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-MediumItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-MediumItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-MediumItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: normal;
    src: url('../assets/fonts/cera-pro/CeraPro-RegularItalic.eot');
    src: local('Cera Pro Regular Italic'), local('CeraPro-RegularItalic'),
      url('../assets/fonts/cera-pro/CeraPro-RegularItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-RegularItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-RegularItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-RegularItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: 900;
    src: url('../assets/fonts/cera-pro/CeraPro-BlackItalic.eot');
    src: local('Cera Pro Black Italic'), local('CeraPro-BlackItalic'),
      url('../assets/fonts/cera-pro/CeraPro-BlackItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-BlackItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-BlackItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-BlackItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: 500;
    src: url('../assets/fonts/cera-pro/CeraPro-Medium.eot');
    src: local('Cera Pro Medium'), local('CeraPro-Medium'),
      url('../assets/fonts/cera-pro/CeraPro-Medium.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Medium.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Medium.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Medium.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: bold;
    src: url('../assets/fonts/cera-pro/CeraPro-BoldItalic.eot');
    src: local('Cera Pro Bold Italic'), local('CeraPro-BoldItalic'),
      url('../assets/fonts/cera-pro/CeraPro-BoldItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-BoldItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-BoldItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-BoldItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: 100;
    src: url('../assets/fonts/cera-pro/CeraPro-ThinItalic.eot');
    src: local('Cera Pro Thin Italic'), local('CeraPro-ThinItalic'),
      url('../assets/fonts/cera-pro/CeraPro-ThinItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-ThinItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-ThinItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-ThinItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: italic;
    font-weight: 300;
    src: url('../assets/fonts/cera-pro/CeraPro-LightItalic.eot');
    src: local('Cera Pro Light Italic'), local('CeraPro-LightItalic'),
      url('../assets/fonts/cera-pro/CeraPro-LightItalic.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-LightItalic.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-LightItalic.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-LightItalic.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: 900;
    src: url('../assets/fonts/cera-pro/CeraPro-Black.eot');
    src: local('Cera Pro Black'), local('CeraPro-Black'),
      url('../assets/fonts/cera-pro/CeraPro-Black.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Black.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Black.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Black.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: bold;
    src: url('../assets/fonts/cera-pro/CeraPro-Bold.eot');
    src: local('Cera Pro Bold'), local('CeraPro-Bold'),
      url('../assets/fonts/cera-pro/CeraPro-Bold.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Bold.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Bold.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Bold.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: normal;
    src: url('../assets/fonts/cera-pro/CeraPro-Regular.eot');
    src: local('Cera Pro Regular'), local('CeraPro-Regular'),
      url('../assets/fonts/cera-pro/CeraPro-Regular.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Regular.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Regular.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Regular.ttf') format('truetype');
  }

  @font-face {
    font-family: 'Cera Pro';
    font-style: normal;
    font-weight: 100;
    src: url('../assets/fonts/cera-pro/CeraPro-Thin.eot');
    src: local('Cera Pro Thin'), local('CeraPro-Thin'),
      url('../assets/fonts/cera-pro/CeraPro-Thin.eot?#iefix') format('embedded-opentype'),
      url('../assets/fonts/cera-pro/CeraPro-Thin.woff2') format('woff2'),
      url('../assets/fonts/cera-pro/CeraPro-Thin.woff') format('woff'),
      url('../assets/fonts/cera-pro/CeraPro-Thin.ttf') format('truetype');
  }
`;
