import { css } from 'lit';

export default css`
/* autogenerated by scrips/make-dt-css.js */


/* ------------------- ./src/tokens/css/000-dt-global-klik-colors.css ----------------------*/
/*
* Global DT Color Primitives
*/
:root {
  /* slate */
  --dt-global-klik-color-slate-10: 252 252 252;
  --dt-global-klik-color-slate-30: 248 248 248;
  --dt-global-klik-color-slate-50: 241 241 241;
  --dt-global-klik-color-slate-100: 227 227 225;
  --dt-global-klik-color-slate-200: 207 207 204;
  --dt-global-klik-color-slate-300: 178 178 176;
  --dt-global-klik-color-slate-400: 150 150 148;
  --dt-global-klik-color-slate-500: 118 118 116;
  --dt-global-klik-color-slate-600: 97 97 95;
  --dt-global-klik-color-slate-700: 77 77 75;
  --dt-global-klik-color-slate-800: 59 59 57;
  --dt-global-klik-color-slate-900: 41 41 40;

  /* turquoise */
  --dt-global-klik-color-turquoise-10: 250 253 253;
  --dt-global-klik-color-turquoise-30: 242 251 252;
  --dt-global-klik-color-turquoise-50: 223 242 245;
  --dt-global-klik-color-turquoise-100: 194 236 242;
  --dt-global-klik-color-turquoise-200: 139 220 232;
  --dt-global-klik-color-turquoise-300: 81 196 214;
  --dt-global-klik-color-turquoise-400: 31 163 184;
  --dt-global-klik-color-turquoise-500: 6 130 148;
  --dt-global-klik-color-turquoise-600: 1 105 120;
  --dt-global-klik-color-turquoise-700: 1 82 94;
  --dt-global-klik-color-turquoise-800: 4 63 71;
  --dt-global-klik-color-turquoise-900: 6 45 51;

  /* teal */
  --dt-global-klik-color-teal-10: 250 252 252;
  --dt-global-klik-color-teal-30: 245 249 250;
  --dt-global-klik-color-teal-50: 233 242 245;
  --dt-global-klik-color-teal-100: 211 231 237;
  --dt-global-klik-color-teal-200: 177 211 222;
  --dt-global-klik-color-teal-300: 141 186 201;
  --dt-global-klik-color-teal-400: 97 152 171;
  --dt-global-klik-color-teal-500: 70 123 140;
  --dt-global-klik-color-teal-600: 55 104 120;
  --dt-global-klik-color-teal-700: 41 79 92;
  --dt-global-klik-color-teal-800: 32 60 69;
  --dt-global-klik-color-teal-900: 21 36 41;

  /* light-blue */
  --dt-global-klik-color-light-blue-10: 249 251 252;
  --dt-global-klik-color-light-blue-30: 245 248 250;
  --dt-global-klik-color-light-blue-50: 232 242 250;
  --dt-global-klik-color-light-blue-100: 202 229 250;
  --dt-global-klik-color-light-blue-200: 166 211 247;
  --dt-global-klik-color-light-blue-300: 121 188 242;
  --dt-global-klik-color-light-blue-400: 69 153 222;
  --dt-global-klik-color-light-blue-500: 36 123 191;
  --dt-global-klik-color-light-blue-600: 23 102 166;
  --dt-global-klik-color-light-blue-700: 15 83 138;
  --dt-global-klik-color-light-blue-800: 12 65 107;
  --dt-global-klik-color-light-blue-900: 10 44 71;

  /* dark-blue */
  --dt-global-klik-color-dark-blue-10: 250 251 252;
  --dt-global-klik-color-dark-blue-30: 242 246 252;
  --dt-global-klik-color-dark-blue-50: 232 240 252;
  --dt-global-klik-color-dark-blue-100: 210 225 252;
  --dt-global-klik-color-dark-blue-200: 177 204 250;
  --dt-global-klik-color-dark-blue-300: 138 177 242;
  --dt-global-klik-color-dark-blue-400: 95 145 232;
  --dt-global-klik-color-dark-blue-500: 52 110 209;
  --dt-global-klik-color-dark-blue-600: 25 81 178;
  --dt-global-klik-color-dark-blue-700: 12 57 135;
  --dt-global-klik-color-dark-blue-800: 11 47 110;
  --dt-global-klik-color-dark-blue-900: 11 37 82;

  /* purple */
  --dt-global-klik-color-purple-10: 251 250 252;
  --dt-global-klik-color-purple-30: 248 245 252;
  --dt-global-klik-color-purple-50: 243 237 252;
  --dt-global-klik-color-purple-100: 232 220 250;
  --dt-global-klik-color-purple-200: 212 191 245;
  --dt-global-klik-color-purple-300: 191 162 235;
  --dt-global-klik-color-purple-400: 162 126 217;
  --dt-global-klik-color-purple-500: 138 98 196;
  --dt-global-klik-color-purple-600: 115 76 173;
  --dt-global-klik-color-purple-700: 91 58 140;
  --dt-global-klik-color-purple-800: 69 43 107;
  --dt-global-klik-color-purple-900: 46 32 66;

  /* magenta */
  --dt-global-klik-color-magenta-10: 252 250 251;
  --dt-global-klik-color-magenta-30: 252 245 248;
  --dt-global-klik-color-magenta-50: 252 235 243;
  --dt-global-klik-color-magenta-100: 252 212 231;
  --dt-global-klik-color-magenta-200: 250 182 214;
  --dt-global-klik-color-magenta-300: 242 148 192;
  --dt-global-klik-color-magenta-400: 229 103 162;
  --dt-global-klik-color-magenta-500: 207 62 129;
  --dt-global-klik-color-magenta-600: 178 37 103;
  --dt-global-klik-color-magenta-700: 140 22 77;
  --dt-global-klik-color-magenta-800: 97 19 56;
  --dt-global-klik-color-magenta-900: 64 22 42;

  /* copper */
  --dt-global-klik-color-copper-10: 255 253 250;
  --dt-global-klik-color-copper-30: 252 247 240;
  --dt-global-klik-color-copper-50: 250 239 225;
  --dt-global-klik-color-copper-100: 251 220 183;
  --dt-global-klik-color-copper-200: 243 196 139;
  --dt-global-klik-color-copper-300: 227 166 91;
  --dt-global-klik-color-copper-400: 204 138 55;
  --dt-global-klik-color-copper-500: 163 104 31;
  --dt-global-klik-color-copper-600: 133 83 21;
  --dt-global-klik-color-copper-700: 101 65 19;
  --dt-global-klik-color-copper-800: 74 50 20;
  --dt-global-klik-color-copper-900: 51 37 20;

  /* information */
  --dt-global-klik-color-information-50: 230 245 252;
  --dt-global-klik-color-information-100: 197 234 252;
  --dt-global-klik-color-information-400: 23 159 227;
  --dt-global-klik-color-information-500: 0 124 186;
  --dt-global-klik-color-information-600: 5 104 153;

  /* success */
  --dt-global-klik-color-success-50: 232 247 230;
  --dt-global-klik-color-success-100: 211 247 208;
  --dt-global-klik-color-success-400: 28 178 12;
  --dt-global-klik-color-success-500: 16 138 6;
  --dt-global-klik-color-success-600: 17 110 9;

  /* warning */
  --dt-global-klik-color-warning-50: 252 242 219;
  --dt-global-klik-color-warning-100: 252 233 192;
  --dt-global-klik-color-warning-400: 242 167 5;
  --dt-global-klik-color-warning-500: 158 108 0;
  --dt-global-klik-color-warning-600: 128 87 0;

  /* error */
  --dt-global-klik-color-error-50: 255 242 242;
  --dt-global-klik-color-error-100: 255 222 222;
  --dt-global-klik-color-error-400: 245 91 91;
  --dt-global-klik-color-error-500: 219 31 31;
  --dt-global-klik-color-error-600: 178 7 7;

  --dt-global-klik-color-black: 10 10 10;
  --dt-global-klik-color-white: 255 255 255;
}


/* ------------------- ./src/tokens/css/000-dt-global-klik-ui.css ----------------------*/
/**
 * Manually copied style keys from klik-ui
 * TODO: Should come from Style-Dictionary
 *
 * Left-hand keys  : --dt-global-klikui-*
 * Right-hand keys : hardcoded value
 *
 */
:root {
  /* Shadows */
  --dt-global-klikui-shadows-button: 0px 1px 0px rgba(0, 0, 0, 0.1), inset 0px -1px 0px rgba(0, 0, 0, 0.15);
  --dt-global-klikui-shadows--1: inset 0px 2px 0px rgba(0, 0, 0, 0.1);

  /* Borders */
  --dt-global-klikui-border-none: 0;
  --dt-global-klikui-border-1px: 1px solid;
  --dt-global-klikui-border-2px: 2px solid;
  --dt-global-klikui-border-4px: 4px solid;
  --dt-global-klikui-border-8px: 8px solid;

  /* Radius */
  --dt-global-klikui-radii-none: 0;
  --dt-global-klikui-radii-sm: 0.125rem; /* 2px */
  --dt-global-klikui-radii-base: 0.25rem; /* 4px */
  --dt-global-klikui-radii-md: 0.375rem; /* 6px */
  --dt-global-klikui-radii-lg: 0.5rem; /* 8px */
  --dt-global-klikui-radii-xl: 0.75rem; /* 12px */
  --dt-global-klikui-radii-2xl: 1rem; /* 16px */
  --dt-global-klikui-radii-3xl: 1.5rem; /* 24px */
  --dt-global-klikui-radii-full: 9999px;

  /* Sizes */
  --dt-global-klikui-size-input-small: 2rem;
  --dt-global-klikui-size-input-medium: 3rem;
  --dt-global-klikui-size-input-large: 4rem;

  /* Typo */
  --dt-global-klikui-fontfamily-body: 'Cera Pro';
  --dt-global-klikui-fontfamily-heading: 'Cera Pro';
  --dt-global-klikui-fontfamily-mono: 'SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace';

  --dt-global-klikui-fontweight-hairline: 100;
  --dt-global-klikui-fontweight-thin: 200;
  --dt-global-klikui-fontweight-light: 300;
  --dt-global-klikui-fontweight-normal: 400;
  --dt-global-klikui-fontweight-medium: 500;
  --dt-global-klikui-fontweight-semibold: 600;
  --dt-global-klikui-fontweight-bold: 700;
  --dt-global-klikui-fontweight-extrabold: 800;
  --dt-global-klikui-fontweight-black: 900;

  --dt-global-klikui-fontsize-xs: 0.75rem;
  --dt-global-klikui-fontsize-sm: 0.875rem;
  --dt-global-klikui-fontsize-md: 1rem;
  --dt-global-klikui-fontsize-lg: 1.125rem;
  --dt-global-klikui-fontsize-xl: 1.25rem;
  --dt-global-klikui-fontsize-2xl: 1.5625rem;
  --dt-global-klikui-fontsize-3xl: 1.9375rem;
  --dt-global-klikui-fontsize-4xl: 2.4375rem;
  --dt-global-klikui-fontsize-5xl: 3.0625rem;
  --dt-global-klikui-fontsize-6xl: 3.8125rem;
  --dt-global-klikui-fontsize-7xl: 4.75rem;
  --dt-global-klikui-fontsize-8xl: 5.9375rem;

  --dt-global-klikui-lineheight-xs: 1rem;
  --dt-global-klikui-lineheight-sm: 1.25rem;
  --dt-global-klikui-lineheight-md: 1.5rem;
  --dt-global-klikui-lineheight-lg: 1.75rem;
  --dt-global-klikui-lineheight-xl: 2rem;
  --dt-global-klikui-lineheight-2xl: 2.25rem;
  --dt-global-klikui-lineheight-3xl: 2.5rem;
  --dt-global-klikui-lineheight-4xl: 3rem;
  --dt-global-klikui-lineheight-5xl: 3.75rem;
  --dt-global-klikui-lineheight-6xl: 4.5rem;
  --dt-global-klikui-lineheight-7xl: 5.5rem;
  --dt-global-klikui-lineheight-8xl: 6.75rem;
}


/* ------------------- ./src/tokens/css/000-dt-global-tw-colors.css ----------------------*/
/**
 * Just some colors from tailwind
 */
:root {
  /* Blue Gray */
  --dt-global-tw-color-blue-gray-50: 248 250 252;
  --dt-global-tw-color-blue-gray-100: 241 245 249;
  --dt-global-tw-color-blue-gray-200: 226 232 240;
  --dt-global-tw-color-blue-gray-300: 203 213 225;
  --dt-global-tw-color-blue-gray-400: 148 163 184;
  --dt-global-tw-color-blue-gray-500: 100 116 139;
  --dt-global-tw-color-blue-gray-600: 71 85 105;
  --dt-global-tw-color-blue-gray-700: 51 65 85;
  --dt-global-tw-color-blue-gray-800: 30 41 59;
  --dt-global-tw-color-blue-gray-900: 15 23 42;
  --dt-global-tw-color-blue-gray-950: 10 16 30;

  /* Cool Gray */
  --dt-global-tw-color-cool-gray-50: 249 250 251;
  --dt-global-tw-color-cool-gray-100: 243 244 246;
  --dt-global-tw-color-cool-gray-200: 229 231 235;
  --dt-global-tw-color-cool-gray-300: 209 213 219;
  --dt-global-tw-color-cool-gray-400: 156 163 175;
  --dt-global-tw-color-cool-gray-500: 107 114 128;
  --dt-global-tw-color-cool-gray-600: 75 85 99;
  --dt-global-tw-color-cool-gray-700: 55 65 81;
  --dt-global-tw-color-cool-gray-800: 31 41 55;
  --dt-global-tw-color-cool-gray-900: 17 24 39;
  --dt-global-tw-color-cool-gray-950: 12 17 29;

  /* Gray */
  --dt-global-tw-color-gray-50: 250 250 250;
  --dt-global-tw-color-gray-100: 244 244 245;
  --dt-global-tw-color-gray-200: 228 228 231;
  --dt-global-tw-color-gray-300: 212 212 216;
  --dt-global-tw-color-gray-400: 161 161 170;
  --dt-global-tw-color-gray-500: 113 113 122;
  --dt-global-tw-color-gray-600: 82 82 91;
  --dt-global-tw-color-gray-700: 63 63 70;
  --dt-global-tw-color-gray-800: 39 39 42;
  --dt-global-tw-color-gray-900: 24 24 27;
  --dt-global-tw-color-gray-950: 19 19 22;

  /* True Gray */
  --dt-global-tw-color-true-gray-50: 250 250 250;
  --dt-global-tw-color-true-gray-100: 245 245 245;
  --dt-global-tw-color-true-gray-200: 229 229 229;
  --dt-global-tw-color-true-gray-300: 212 212 212;
  --dt-global-tw-color-true-gray-400: 163 163 163;
  --dt-global-tw-color-true-gray-500: 115 115 115;
  --dt-global-tw-color-true-gray-600: 82 82 82;
  --dt-global-tw-color-true-gray-700: 64 64 64;
  --dt-global-tw-color-true-gray-800: 38 38 38;
  --dt-global-tw-color-true-gray-900: 23 23 23;
  --dt-global-tw-color-true-gray-950: 17 17 17;

  /* Warm Gray */
  --dt-global-tw-color-warm-gray-50: 250 250 249;
  --dt-global-tw-color-warm-gray-100: 245 245 244;
  --dt-global-tw-color-warm-gray-200: 231 229 228;
  --dt-global-tw-color-warm-gray-300: 214 211 209;
  --dt-global-tw-color-warm-gray-400: 168 162 158;
  --dt-global-tw-color-warm-gray-500: 120 113 108;
  --dt-global-tw-color-warm-gray-600: 87 83 78;
  --dt-global-tw-color-warm-gray-700: 68 64 60;
  --dt-global-tw-color-warm-gray-800: 41 37 36;
  --dt-global-tw-color-warm-gray-900: 28 25 23;
  --dt-global-tw-color-warm-gray-950: 19 18 16;

  /* Red */
  --dt-global-tw-color-red-50: 254 242 242;
  --dt-global-tw-color-red-100: 254 226 226;
  --dt-global-tw-color-red-200: 254 202 202;
  --dt-global-tw-color-red-300: 252 165 165;
  --dt-global-tw-color-red-400: 248 113 113;
  --dt-global-tw-color-red-500: 239 68 68;
  --dt-global-tw-color-red-600: 220 38 38;
  --dt-global-tw-color-red-700: 185 28 28;
  --dt-global-tw-color-red-800: 153 27 27;
  --dt-global-tw-color-red-900: 127 29 29;
  --dt-global-tw-color-red-950: 80 20 20;

  /* Orange */
  --dt-global-tw-color-orange-50: 255 247 237;
  --dt-global-tw-color-orange-100: 255 237 213;
  --dt-global-tw-color-orange-200: 254 215 170;
  --dt-global-tw-color-orange-300: 253 186 116;
  --dt-global-tw-color-orange-400: 251 146 60;
  --dt-global-tw-color-orange-500: 249 115 22;
  --dt-global-tw-color-orange-600: 234 88 12;
  --dt-global-tw-color-orange-700: 194 65 12;
  --dt-global-tw-color-orange-800: 154 52 18;
  --dt-global-tw-color-orange-900: 124 45 18;
  --dt-global-tw-color-orange-950: 82 32 15;

  /* Amber */
  --dt-global-tw-color-amber-50: 255 251 235;
  --dt-global-tw-color-amber-100: 254 243 199;
  --dt-global-tw-color-amber-200: 253 230 138;
  --dt-global-tw-color-amber-300: 252 211 77;
  --dt-global-tw-color-amber-400: 251 191 36;
  --dt-global-tw-color-amber-500: 245 158 11;
  --dt-global-tw-color-amber-600: 217 119 6;
  --dt-global-tw-color-amber-700: 180 83 9;
  --dt-global-tw-color-amber-800: 146 64 14;
  --dt-global-tw-color-amber-900: 120 53 15;
  --dt-global-tw-color-amber-950: 74 35 11;

  /* Yellow */
  --dt-global-tw-color-yellow-50: 254 252 232;
  --dt-global-tw-color-yellow-100: 254 249 195;
  --dt-global-tw-color-yellow-200: 254 240 138;
  --dt-global-tw-color-yellow-300: 253 224 71;
  --dt-global-tw-color-yellow-400: 250 204 21;
  --dt-global-tw-color-yellow-500: 234 179 8;
  --dt-global-tw-color-yellow-600: 202 138 4;
  --dt-global-tw-color-yellow-700: 161 98 7;
  --dt-global-tw-color-yellow-800: 133 77 14;
  --dt-global-tw-color-yellow-900: 113 63 18;
  --dt-global-tw-color-yellow-950: 60 38 11;

  /* Lime */
  --dt-global-tw-color-lime-50: 247 254 231;
  --dt-global-tw-color-lime-100: 236 252 203;
  --dt-global-tw-color-lime-200: 217 249 157;
  --dt-global-tw-color-lime-300: 190 242 100;
  --dt-global-tw-color-lime-400: 163 230 53;
  --dt-global-tw-color-lime-500: 132 204 22;
  --dt-global-tw-color-lime-600: 101 163 13;
  --dt-global-tw-color-lime-700: 77 124 15;
  --dt-global-tw-color-lime-800: 63 98 18;
  --dt-global-tw-color-lime-900: 54 83 20;
  --dt-global-tw-color-lime-950: 38 57 14;

  /* Green */
  --dt-global-tw-color-green-50: 240 253 244;
  --dt-global-tw-color-green-100: 220 252 231;
  --dt-global-tw-color-green-200: 187 247 208;
  --dt-global-tw-color-green-300: 134 239 172;
  --dt-global-tw-color-green-400: 74 222 128;
  --dt-global-tw-color-green-500: 34 197 94;
  --dt-global-tw-color-green-600: 22 163 74;
  --dt-global-tw-color-green-700: 21 128 61;
  --dt-global-tw-color-green-800: 22 101 52;
  --dt-global-tw-color-green-900: 20 83 45;
  --dt-global-tw-color-green-950: 12 49 27;

  /* Emerald */
  --dt-global-tw-color-emerald-50: 236 253 245;
  --dt-global-tw-color-emerald-100: 209 250 229;
  --dt-global-tw-color-emerald-200: 167 243 208;
  --dt-global-tw-color-emerald-300: 110 231 183;
  --dt-global-tw-color-emerald-400: 52 211 153;
  --dt-global-tw-color-emerald-500: 16 185 129;
  --dt-global-tw-color-emerald-600: 5 150 105;
  --dt-global-tw-color-emerald-700: 4 120 87;
  --dt-global-tw-color-emerald-800: 6 95 70;
  --dt-global-tw-color-emerald-900: 6 78 59;
  --dt-global-tw-color-emerald-950: 3 45 34;

  /* Teal */
  --dt-global-tw-color-teal-50: 240 253 250;
  --dt-global-tw-color-teal-100: 204 251 241;
  --dt-global-tw-color-teal-200: 153 246 228;
  --dt-global-tw-color-teal-300: 94 234 212;
  --dt-global-tw-color-teal-400: 45 212 191;
  --dt-global-tw-color-teal-500: 20 184 166;
  --dt-global-tw-color-teal-600: 13 148 136;
  --dt-global-tw-color-teal-700: 15 118 110;
  --dt-global-tw-color-teal-800: 17 94 89;
  --dt-global-tw-color-teal-900: 19 78 74;
  --dt-global-tw-color-teal-950: 12 46 44;

  /* Cyan */
  --dt-global-tw-color-cyan-50: 236 254 255;
  --dt-global-tw-color-cyan-100: 207 250 254;
  --dt-global-tw-color-cyan-200: 165 243 252;
  --dt-global-tw-color-cyan-300: 103 232 249;
  --dt-global-tw-color-cyan-400: 34 211 238;
  --dt-global-tw-color-cyan-500: 6 182 212;
  --dt-global-tw-color-cyan-600: 8 145 178;
  --dt-global-tw-color-cyan-700: 14 116 144;
  --dt-global-tw-color-cyan-800: 21 94 117;
  --dt-global-tw-color-cyan-900: 22 78 99;
  --dt-global-tw-color-cyan-950: 16 52 66;

  /* Sky */
  --dt-global-tw-color-sky-50: 240 249 255;
  --dt-global-tw-color-sky-100: 224 242 254;
  --dt-global-tw-color-sky-200: 186 230 253;
  --dt-global-tw-color-sky-300: 125 211 252;
  --dt-global-tw-color-sky-400: 56 189 248;
  --dt-global-tw-color-sky-500: 14 165 233;
  --dt-global-tw-color-sky-600: 2 132 199;
  --dt-global-tw-color-sky-700: 3 105 161;
  --dt-global-tw-color-sky-800: 7 89 133;
  --dt-global-tw-color-sky-900: 12 74 110;
  --dt-global-tw-color-sky-950: 11 50 73;

  /* Blue */
  --dt-global-tw-color-blue-50: 239 246 255;
  --dt-global-tw-color-blue-100: 219 234 254;
  --dt-global-tw-color-blue-200: 191 219 254;
  --dt-global-tw-color-blue-300: 147 197 253;
  --dt-global-tw-color-blue-400: 96 165 250;
  --dt-global-tw-color-blue-500: 59 130 246;
  --dt-global-tw-color-blue-600: 37 99 235;
  --dt-global-tw-color-blue-700: 29 78 216;
  --dt-global-tw-color-blue-800: 30 64 175;
  --dt-global-tw-color-blue-900: 30 58 138;
  --dt-global-tw-color-blue-950: 21 33 73;

  /* Indigo */
  --dt-global-tw-color-indigo-50: 238 242 255;
  --dt-global-tw-color-indigo-100: 224 231 255;
  --dt-global-tw-color-indigo-200: 199 210 254;
  --dt-global-tw-color-indigo-300: 165 180 252;
  --dt-global-tw-color-indigo-400: 129 140 248;
  --dt-global-tw-color-indigo-500: 99 102 241;
  --dt-global-tw-color-indigo-600: 79 70 229;
  --dt-global-tw-color-indigo-700: 67 56 202;
  --dt-global-tw-color-indigo-800: 55 48 163;
  --dt-global-tw-color-indigo-900: 49 46 129;
  --dt-global-tw-color-indigo-950: 36 33 84;

  /* Violet */
  --dt-global-tw-color-violet-50: 245 243 255;
  --dt-global-tw-color-violet-100: 237 233 254;
  --dt-global-tw-color-violet-200: 221 214 254;
  --dt-global-tw-color-violet-300: 196 181 253;
  --dt-global-tw-color-violet-400: 167 139 250;
  --dt-global-tw-color-violet-500: 139 92 246;
  --dt-global-tw-color-violet-600: 124 58 237;
  --dt-global-tw-color-violet-700: 109 40 217;
  --dt-global-tw-color-violet-800: 91 33 182;
  --dt-global-tw-color-violet-900: 76 29 149;
  --dt-global-tw-color-violet-950: 49 21 88;

  /* Purple */
  --dt-global-tw-color-purple-50: 250 245 255;
  --dt-global-tw-color-purple-100: 243 232 255;
  --dt-global-tw-color-purple-200: 233 213 255;
  --dt-global-tw-color-purple-300: 216 180 254;
  --dt-global-tw-color-purple-400: 192 132 252;
  --dt-global-tw-color-purple-500: 168 85 247;
  --dt-global-tw-color-purple-600: 147 51 234;
  --dt-global-tw-color-purple-700: 126 34 206;
  --dt-global-tw-color-purple-800: 107 33 168;
  --dt-global-tw-color-purple-900: 88 28 135;
  --dt-global-tw-color-purple-950: 47 17 67;

  /* Fuchsia */
  --dt-global-tw-color-fuchsia-50: 253 244 255;
  --dt-global-tw-color-fuchsia-100: 250 232 255;
  --dt-global-tw-color-fuchsia-200: 245 208 254;
  --dt-global-tw-color-fuchsia-300: 240 171 252;
  --dt-global-tw-color-fuchsia-400: 232 121 249;
  --dt-global-tw-color-fuchsia-500: 217 70 239;
  --dt-global-tw-color-fuchsia-600: 192 38 211;
  --dt-global-tw-color-fuchsia-700: 162 28 175;
  --dt-global-tw-color-fuchsia-800: 134 25 143;
  --dt-global-tw-color-fuchsia-900: 112 26 117;
  --dt-global-tw-color-fuchsia-950: 56 16 58;

  /* Pink */
  --dt-global-tw-color-pink-50: 253 242 248;
  --dt-global-tw-color-pink-100: 252 231 243;
  --dt-global-tw-color-pink-200: 251 207 232;
  --dt-global-tw-color-pink-300: 249 168 212;
  --dt-global-tw-color-pink-400: 244 114 182;
  --dt-global-tw-color-pink-500: 236 72 153;
  --dt-global-tw-color-pink-600: 219 39 119;
  --dt-global-tw-color-pink-700: 190 24 93;
  --dt-global-tw-color-pink-800: 157 23 77;
  --dt-global-tw-color-pink-900: 131 24 67;
  --dt-global-tw-color-pink-950: 67 14 35;

  /* Rose */
  --dt-global-tw-color-rose-50: 255 241 242;
  --dt-global-tw-color-rose-100: 255 228 230;
  --dt-global-tw-color-rose-200: 254 205 211;
  --dt-global-tw-color-rose-300: 253 164 175;
  --dt-global-tw-color-rose-400: 251 113 133;
  --dt-global-tw-color-rose-500: 244 63 94;
  --dt-global-tw-color-rose-600: 225 29 72;
  --dt-global-tw-color-rose-700: 190 18 60;
  --dt-global-tw-color-rose-800: 159 18 57;
  --dt-global-tw-color-rose-900: 136 19 55;
  --dt-global-tw-color-rose-950: 74 13 32;
}


/* ------------------- ./src/tokens/css/100-slk-defaults.css ----------------------*/
/***
* A complete set of defaults for all exposed component keys
*
* To redefine a value, add the key(s) to dtx-map (and ideally dtx-alias)
***/

:root,
:host,
:root.klik-mode-light {
  /*
* Color Primitives
*/

  /* Green */
  --klik-color-green-50: 240 253 244;
  --klik-color-green-100: 220 252 231;
  --klik-color-green-200: 187 247 208;
  --klik-color-green-300: 134 239 172;
  --klik-color-green-400: 74 222 128;
  --klik-color-green-500: 34 197 94;
  --klik-color-green-600: 22 163 74;
  --klik-color-green-700: 21 128 61;
  --klik-color-green-800: 22 101 52;
  --klik-color-green-900: 20 83 45;
  --klik-color-green-950: 12 49 27;

  /* Amber */
  --klik-color-amber-50: 255 251 235;
  --klik-color-amber-100: 254 243 199;
  --klik-color-amber-200: 253 230 138;
  --klik-color-amber-300: 252 211 77;
  --klik-color-amber-400: 251 191 36;
  --klik-color-amber-500: 245 158 11;
  --klik-color-amber-600: 217 119 6;
  --klik-color-amber-700: 180 83 9;
  --klik-color-amber-800: 146 64 14;
  --klik-color-amber-900: 120 53 15;
  --klik-color-amber-950: 74 35 11;

  /* Red */
  --klik-color-red-50: 254 242 242;
  --klik-color-red-100: 254 226 226;
  --klik-color-red-200: 254 202 202;
  --klik-color-red-300: 252 165 165;
  --klik-color-red-400: 248 113 113;
  --klik-color-red-500: 239 68 68;
  --klik-color-red-600: 220 38 38;
  --klik-color-red-700: 185 28 28;
  --klik-color-red-800: 153 27 27;
  --klik-color-red-900: 127 29 29;
  --klik-color-red-950: 80 20 20;

  /* Gray */
  --klik-color-gray-50: 250 250 250;
  --klik-color-gray-100: 244 244 245;
  --klik-color-gray-200: 228 228 231;
  --klik-color-gray-300: 212 212 216;
  --klik-color-gray-400: 161 161 170;
  --klik-color-gray-500: 113 113 122;
  --klik-color-gray-600: 82 82 91;
  --klik-color-gray-700: 63 63 70;
  --klik-color-gray-800: 39 39 42;
  --klik-color-gray-900: 24 24 27;
  --klik-color-gray-950: 19 19 22;

  /* Sky (used as primary) */
  --klik-color-sky-50: 240 249 255;
  --klik-color-sky-100: 224 242 254;
  --klik-color-sky-200: 186 230 253;
  --klik-color-sky-300: 125 211 252;
  --klik-color-sky-400: 56 189 248;
  --klik-color-sky-500: 14 165 233;
  --klik-color-sky-600: 2 132 199;
  --klik-color-sky-700: 3 105 161;
  --klik-color-sky-800: 7 89 133;
  --klik-color-sky-900: 12 74 110;
  --klik-color-sky-950: 11 50 73;

  /*
* Theme Colors
*/

  /* Primary */
  --klik-color-primary-50: var(--klik-color-sky-50);
  --klik-color-primary-100: var(--klik-color-sky-100);
  --klik-color-primary-200: var(--klik-color-sky-200);
  --klik-color-primary-300: var(--klik-color-sky-300);
  --klik-color-primary-400: var(--klik-color-sky-400);
  --klik-color-primary-500: var(--klik-color-sky-500);
  --klik-color-primary-600: var(--klik-color-sky-600);
  --klik-color-primary-700: var(--klik-color-sky-700);
  --klik-color-primary-800: var(--klik-color-sky-800);
  --klik-color-primary-900: var(--klik-color-sky-900);
  --klik-color-primary-950: var(--klik-color-sky-950);

  /* Success */
  --klik-color-success-50: var(--klik-color-green-50);
  --klik-color-success-100: var(--klik-color-green-100);
  --klik-color-success-200: var(--klik-color-green-200);
  --klik-color-success-300: var(--klik-color-green-300);
  --klik-color-success-400: var(--klik-color-green-400);
  --klik-color-success-500: var(--klik-color-green-500);
  --klik-color-success-600: var(--klik-color-green-600);
  --klik-color-success-700: var(--klik-color-green-700);
  --klik-color-success-800: var(--klik-color-green-800);
  --klik-color-success-900: var(--klik-color-green-900);
  --klik-color-success-950: var(--klik-color-green-950);

  /* Warning */
  --klik-color-warning-50: var(--klik-color-amber-50);
  --klik-color-warning-100: var(--klik-color-amber-100);
  --klik-color-warning-200: var(--klik-color-amber-200);
  --klik-color-warning-300: var(--klik-color-amber-300);
  --klik-color-warning-400: var(--klik-color-amber-400);
  --klik-color-warning-500: var(--klik-color-amber-500);
  --klik-color-warning-600: var(--klik-color-amber-600);
  --klik-color-warning-700: var(--klik-color-amber-700);
  --klik-color-warning-800: var(--klik-color-amber-800);
  --klik-color-warning-900: var(--klik-color-amber-900);
  --klik-color-warning-950: var(--klik-color-amber-950);

  /* Danger */
  --klik-color-danger-50: var(--klik-color-red-50);
  --klik-color-danger-100: var(--klik-color-red-100);
  --klik-color-danger-200: var(--klik-color-red-200);
  --klik-color-danger-300: var(--klik-color-red-300);
  --klik-color-danger-400: var(--klik-color-red-400);
  --klik-color-danger-500: var(--klik-color-red-500);
  --klik-color-danger-600: var(--klik-color-red-600);
  --klik-color-danger-700: var(--klik-color-red-700);
  --klik-color-danger-800: var(--klik-color-red-800);
  --klik-color-danger-900: var(--klik-color-red-900);
  --klik-color-danger-950: var(--klik-color-red-950);

  /* Neutral */
  --klik-color-neutral-50: var(--klik-color-gray-50);
  --klik-color-neutral-100: var(--klik-color-gray-100);
  --klik-color-neutral-200: var(--klik-color-gray-200);
  --klik-color-neutral-300: var(--klik-color-gray-300);
  --klik-color-neutral-400: var(--klik-color-gray-400);
  --klik-color-neutral-500: var(--klik-color-gray-500);
  --klik-color-neutral-600: var(--klik-color-gray-600);
  --klik-color-neutral-700: var(--klik-color-gray-700);
  --klik-color-neutral-800: var(--klik-color-gray-800);
  --klik-color-neutral-900: var(--klik-color-gray-900);
  --klik-color-neutral-950: var(--klik-color-gray-950);

  /* Neutral (light) */
  --klik-color-neutral-0: 255 255 255;
  --klik-color-neutral-1000: 0 0 0;

  --klik-surface-base: var(--klik-color-neutral-0);
  --klik-surface-base-alt: var(--klik-color-neutral-0);

  /*
* Border radii
*/

  --klik-border-radius-small: 0.125rem; /* 2px */
  --klik-border-radius-medium: 0.25rem; /* 4px */
  --klik-border-radius-large: 0.5rem; /* 8px */
  --klik-border-radius-x-large: 1rem; /* 16px */

  --klik-border-radius-circle: 50%;
  --klik-border-radius-pill: 9999px;

  /*
* Elevations
*/

  --klik-shadow-x-small: 0 1px 2px rgb(var(--klik-color-neutral-500) / 6%);
  --klik-shadow-small: 0 1px 2px rgb(var(--klik-color-neutral-500) / 12%);
  --klik-shadow-medium: 0 2px 4px rgb(var(--klik-color-neutral-500) / 12%);
  --klik-shadow-large: 0 2px 8px rgb(var(--klik-color-neutral-500) / 12%);
  --klik-shadow-x-large: 0 4px 16px rgb(var(--klik-color-neutral-500) / 12%);

  /*
* Surfaces
*/

  --klik-surface-base: var(--klik-color-neutral-0);
  --klik-surface-base-alt: var(--klik-color-neutral-0);

  /*
* Spacings
*/

  --klik-spacing-3x-small: 0.125rem; /* 2px */
  --klik-spacing-2x-small: 0.25rem; /* 4px */
  --klik-spacing-x-small: 0.5rem; /* 8px */
  --klik-spacing-small: 0.75rem; /* 12px */
  --klik-spacing-medium: 1rem; /* 16px */
  --klik-spacing-large: 1.25rem; /* 20px */
  --klik-spacing-x-large: 1.75rem; /* 28px */
  --klik-spacing-2x-large: 2.25rem; /* 36px */
  --klik-spacing-3x-large: 3rem; /* 48px */
  --klik-spacing-4x-large: 4.5rem; /* 72px */

  /*
* Transitions
*/

  --klik-transition-x-slow: 1000ms;
  --klik-transition-slow: 500ms;
  --klik-transition-medium: 250ms;
  --klik-transition-fast: 150ms;
  --klik-transition-x-fast: 50ms;

  /*
* Typography
*/

  /* Fonts */
  --klik-font-mono: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
  --klik-font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif,
    'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
  --klik-font-serif: Georgia, 'Times New Roman', serif;

  /* Font sizes */
  --klik-font-size-2x-small: 0.625rem; /* 10px */
  --klik-font-size-x-small: 0.75rem; /* 12px */
  --klik-font-size-small: 0.875rem; /* 14px */
  --klik-font-size-medium: 1rem; /* 16px */
  --klik-font-size-large: 1.25rem; /* 20px */
  --klik-font-size-x-large: 1.5rem; /* 24px */
  --klik-font-size-2x-large: 2.25rem; /* 36px */
  --klik-font-size-3x-large: 3rem; /* 48px */
  --klik-font-size-4x-large: 4.5rem; /* 72px */

  /* Font weights */
  --klik-font-weight-light: 300;
  --klik-font-weight-normal: 400;
  --klik-font-weight-semibold: 500;
  --klik-font-weight-bold: 700;

  /* Letter spacings */
  --klik-letter-spacing-denser: -0.03em;
  --klik-letter-spacing-dense: -0.015em;
  --klik-letter-spacing-normal: normal;
  --klik-letter-spacing-loose: 0.075em;
  --klik-letter-spacing-looser: 0.15em;

  /* Line heights */
  --klik-line-height-denser: 1;
  --klik-line-height-dense: 1.4;
  --klik-line-height-normal: 1.8;
  --klik-line-height-loose: 2.2;
  --klik-line-height-looser: 2.6;

  /*
* Forms
*/

  /* Focus rings */
  --klik-focus-ring-color: var(--klik-color-primary-500);
  --klik-focus-ring-width: 3px;
  --klik-focus-ring-alpha: 40%;
  --klik-focus-ring: 0 0 0 var(--klik-focus-ring-width) rgb(var(--klik-focus-ring-color) / var(--klik-focus-ring-alpha));

  /* Buttons */
  --klik-button-font-size-small: var(--klik-font-size-x-small);
  --klik-button-font-size-medium: var(--klik-font-size-small);
  --klik-button-font-size-large: var(--klik-font-size-medium);

  /* Inputs */
  --klik-input-height-small: 1.875rem; /* 30px */
  --klik-input-height-medium: 2.5rem; /* 40px */
  --klik-input-height-large: 3.125rem; /* 50px */

  --klik-input-background-color: var(--klik-color-neutral-0);
  --klik-input-background-color-hover: var(--klik-input-background-color);
  --klik-input-background-color-focus: var(--klik-input-background-color);
  --klik-input-background-color-disabled: var(--klik-color-neutral-100);
  --klik-input-border-color: var(--klik-color-neutral-300);
  --klik-input-border-color-hover: var(--klik-color-neutral-400);
  --klik-input-border-color-focus: var(--klik-color-primary-500);
  --klik-input-border-color-disabled: var(--klik-color-neutral-300);
  --klik-input-border-width: 1px;

  --klik-input-border-radius-small: var(--klik-border-radius-medium);
  --klik-input-border-radius-medium: var(--klik-border-radius-medium);
  --klik-input-border-radius-large: var(--klik-border-radius-medium);

  --klik-input-font-family: var(--klik-font-sans);
  --klik-input-font-weight: var(--klik-font-weight-normal);
  --klik-input-font-size-small: var(--klik-font-size-small);
  --klik-input-font-size-medium: var(--klik-font-size-medium);
  --klik-input-font-size-large: var(--klik-font-size-large);
  --klik-input-letter-spacing: var(--klik-letter-spacing-normal);

  --klik-input-color: var(--klik-color-neutral-700);
  --klik-input-color-hover: var(--klik-color-neutral-700);
  --klik-input-color-focus: var(--klik-color-neutral-700);
  --klik-input-color-disabled: var(--klik-color-neutral-900);
  --klik-input-icon-color: var(--klik-color-neutral-500);
  --klik-input-icon-color-hover: var(--klik-color-neutral-600);
  --klik-input-icon-color-focus: var(--klik-color-neutral-600);
  --klik-input-placeholder-color: var(--klik-color-neutral-500);
  --klik-input-placeholder-color-disabled: var(--klik-color-neutral-600);
  --klik-input-spacing-small: var(--klik-spacing-small);
  --klik-input-spacing-medium: var(--klik-spacing-medium);
  --klik-input-spacing-large: var(--klik-spacing-large);

  --klik-input-filled-background-color: var(--klik-color-neutral-100);
  --klik-input-filled-background-color-hover: var(--klik-color-neutral-100);
  --klik-input-filled-background-color-focus: var(--klik-color-neutral-0);
  --klik-input-filled-background-color-disabled: var(--klik-color-neutral-100);
  --klik-input-filled-color: var(--klik-color-neutral-800);
  --klik-input-filled-color-hover: var(--klik-color-neutral-800);
  --klik-input-filled-color-focus: var(--klik-color-neutral-700);
  --klik-input-filled-color-disabled: var(--klik-color-neutral-800);

  /* Labels */
  --klik-input-label-font-size-small: var(--klik-font-size-small);
  --klik-input-label-font-size-medium: var(--klik-font-size-medium);
  --klik-input-label-font-size-large: var(--klik-font-size-large);

  --klik-input-label-color: inherit;

  /* Help text */
  --klik-input-help-text-font-size-small: var(--klik-font-size-x-small);
  --klik-input-help-text-font-size-medium: var(--klik-font-size-small);
  --klik-input-help-text-font-size-large: var(--klik-font-size-medium);

  --klik-input-help-text-color: var(--klik-color-neutral-500);

  /* Toggles (checkboxes, radios, switches) */
  --klik-toggle-size: 1rem;

  /*
* Overlays
*/

  --klik-overlay-background-color: var(--klik-color-blue-gray-500);
  --klik-overlay-opacity: 33%;

  /*
* Panels
*/

  --klik-panel-background-color: var(--klik-surface-base-alt);
  --klik-panel-border-color: var(--klik-color-neutral-200);
  --klik-panel-border-width: 1px;

  /*
* Tooltips
*/

  --klik-tooltip-border-radius: var(--klik-border-radius-medium);
  --klik-tooltip-background-color: var(--klik-color-neutral-800);
  --klik-tooltip-color: var(--klik-color-neutral-0);
  --klik-tooltip-font-family: var(--klik-font-sans);
  --klik-tooltip-font-weight: var(--klik-font-weight-normal);
  --klik-tooltip-font-size: var(--klik-font-size-small);
  --klik-tooltip-line-height: var(--klik-line-height-dense);
  --klik-tooltip-padding: var(--klik-spacing-2x-small) var(--klik-spacing-x-small);
  --klik-tooltip-arrow-size: 5px;
  --klik-tooltip-arrow-start-end-offset: 8px;

  /*
* Z-indexes
*/

  --klik-z-index-drawer: 700;
  --klik-z-index-dialog: 800;
  --klik-z-index-dropdown: 900;
  --klik-z-index-toast: 950;
  --klik-z-index-tooltip: 1000;

  /* Document */
  /* font-size: 16px; Use host (allow client to set this) */
  font-feature-settings: 'kern';

  -webkit-text-size-adjust: 100%;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;

  font-family: var(--klik-font-sans);
  font-size: var(--klik-font-size-medium);
  font-weight: var(--klik-font-weight-normal);
  letter-spacing: var(--klik-letter-spacing-normal);
  line-height: var(--klik-line-height-normal);
  background-color: rgb(var(--klik-surface-base));
  color: rgb(var(--klik-color-neutral-800));
}

/* Redefine select colors for light/dark mode */

:root.klik-mode-dark {
  --klik-color-neutral-0: 24 24 27;
  --klik-color-neutral-1000: 255 255 255;

  --klik-surface-base: var(--klik-color-neutral-0);
  --klik-surface-base-alt: var(--klik-color-neutral-50);

  /* Green */
  --klik-color-green-50: 16 53 31;
  --klik-color-green-100: 25 87 49;
  --klik-color-green-200: 28 106 56;
  --klik-color-green-300: 29 133 65;
  --klik-color-green-400: 32 168 78;
  --klik-color-green-500: 43 202 99;
  --klik-color-green-600: 80 227 133;
  --klik-color-green-700: 139 244 177;
  --klik-color-green-800: 192 252 213;
  --klik-color-green-900: 225 255 236;
  --klik-color-green-950: 245 255 249;

  /* Amber */
  --klik-color-amber-50: 79 39 16;
  --klik-color-amber-100: 125 57 19;
  --klik-color-amber-200: 151 68 19;
  --klik-color-amber-300: 186 88 16;
  --klik-color-amber-400: 223 124 15;
  --klik-color-amber-500: 251 163 21;
  --klik-color-amber-600: 255 196 43;
  --klik-color-amber-700: 255 216 82;
  --klik-color-amber-800: 255 235 143;
  --klik-color-amber-900: 255 248 204;
  --klik-color-amber-950: 255 255 240;

  /* Red */
  --klik-color-red-50: 85 24 24;
  --klik-color-red-100: 132 34 33;
  --klik-color-red-200: 158 33 31;
  --klik-color-red-300: 191 35 32;
  --klik-color-red-400: 226 45 42;
  --klik-color-red-500: 245 74 72;
  --klik-color-red-600: 254 118 118;
  --klik-color-red-700: 255 170 170;
  --klik-color-red-800: 255 207 207;
  --klik-color-red-900: 255 231 231;
  --klik-color-red-950: 255 247 247;

  /* Gray */
  --klik-color-gray-50: 28 28 31;
  --klik-color-gray-100: 33 33 37;
  --klik-color-gray-200: 43 43 46;
  --klik-color-gray-300: 67 67 74;
  --klik-color-gray-400: 86 86 95;
  --klik-color-gray-500: 118 118 127;
  --klik-color-gray-600: 166 166 175;
  --klik-color-gray-700: 217 217 221;
  --klik-color-gray-800: 233 233 236;
  --klik-color-gray-900: 249 249 250;
  --klik-color-gray-950: 255 255 255;

  /* Sky */
  --klik-color-sky-50: 17 54 77;
  --klik-color-sky-100: 20 78 115;
  --klik-color-sky-200: 19 93 138;
  --klik-color-sky-300: 18 109 166;
  --klik-color-sky-400: 22 137 204;
  --klik-color-sky-500: 31 170 238;
  --klik-color-sky-600: 64 194 253;
  --klik-color-sky-700: 130 216 255;
  --klik-color-sky-800: 191 235 255;
  --klik-color-sky-900: 229 247 255;
  --klik-color-sky-950: 245 254 255;
}


/* ------------------- ./src/tokens/css/190-shoelace-mod.css ----------------------*/
/**
 * We have made some modifications to the shoelace styles
 * so it uses a dedicated token for 'primary interaction'
 * We need to make sure there's default values for it:
 */
:root {
  --dt-alias-color-primary-interaction: var(--klik-color-neutral-200);
  --dt-alias-color-primary-interaction-hover: var(--klik-color-neutral-300);
  --dt-alias-color-primary-interaction-text: var(--klik-color-neutral-900);

  --klik-color-primary-interaction: var(--dt-alias-color-primary-interaction);
  --klik-color-primary-interaction-hover: var(--dt-alias-color-primary-interaction-hover);
  --klik-color-primary-interaction-text: var(--dt-alias-color-primary-interaction-text);

  --klik-button-shadow: none;
  --klik-button-border: 0px solid;
  --klik-button-outline-border: 1px solid;

  /* --klik-button-font-size-small: var(--klik-font-size-xsmall);
  --klik-button-font-size-medium: var(--klik-font-size-small);
  --klik-button-font-size-large: var(--klik-font-size-medium); */
}


/* ------------------- ./src/tokens/css/200-dtx-alias.css ----------------------*/
/**
 * Map Globals to Aliasas
 *
 * Left-hand keys  : --dt-alias-*
 * Right-hand keys : --dt-global-* or hardcoded value
 *
 * */

:root.klik-theme-klikui {
  --dt-alias-color-primary-interaction: var(--dt-global-klik-color-light-blue-500);
  --dt-alias-color-primary-interaction-hover: var(--dt-global-klik-color-light-blue-600);
  --dt-alias-color-primary-interaction-text: var(--dt-global-klik-color-white);

  --dt-alias-fontfamily-sans: 'Cera Pro';
  --dt-alias-fontfamily-input: 'Cera Pro';

  /* --dt-alias-color-primary-interaction: 255 0 0;
  --dt-alias-color-primary-interaction-text: 0 0 0; */
}


/* ------------------- ./src/tokens/css/400-dtx-map.css ----------------------*/
/**
 * Map Aliases to Component Styles
 *
 * Left-hand keys  : --klik-*
 * Right-hand keys : --dt-alias-* (or --dt-global-* if used without alias layer)
 *
 * See dtx-defaults-* for keys to redefine/link
 */
:root.klik-theme-klikui {
  /* typo */
  --klik-font-sans: var(--dt-alias-fontfamily-sans);
  --klik-input-font-family: var(--dt-alias-fontfamily-input);

  /* Font sizes */
  --klik-font-size-2x-small: 0.625rem; /* 10px */
  --klik-font-size-x-small: var(--dt-global-klikui-fontsize-xs);
  --klik-font-size-small: var(--dt-global-klikui-fontsize-sm);
  --klik-font-size-medium: var(--dt-global-klikui-fontsize-md);
  --klik-font-size-large: var(--dt-global-klikui-fontsize-lg);
  --klik-font-size-x-large: var(--dt-global-klikui-fontsize-xl);
  --klik-font-size-2x-large: var(--dt-global-klikui-fontsize-2xl);
  --klik-font-size-3x-large: var(--dt-global-klikui-fontsize-3xl);
  --klik-font-size-4x-large: var(--dt-global-klikui-fontsize-4xl);

  /* Font weights */
  --klik-font-weight-light: var(--dt-global-klikui-fontweight-light);
  --klik-font-weight-normal: var(--dt-global-klikui-fontweight-normal);
  --klik-font-weight-medium: var(--dt-global-klikui-fontweight-medium);
  --klik-font-weight-semibold: var(--dt-global-klikui-fontweight-semibold);
  --klik-font-weight-bold: var(--dt-global-klikui-fontweight-bold);

  /* Line heights */
  --klik-line-height-denser: 1;
  --klik-line-height-dense: 1.4;
  --klik-line-height-normal: 1.8;
  --klik-line-height-loose: 2.2;
  --klik-line-height-looser: 2.6;

  /* primary interaction */
  --klik-color-primary-interaction: var(--dt-alias-color-primary-interaction);
  --klik-color-primary-interaction-hover: var(--dt-alias-color-primary-interaction-hover);
  --klik-color-primary-interaction-text: var(--dt-alias-color-primary-interaction-text);

  /* buttons */
  --klik-button-shadow: var(--dt-global-klikui-shadows-button);
  --klik-button-outline-background-hover: var(--dt-global-klik-color-slate-50);

  --klik-button-font-size-small: var(--dt-global-klikui-fontsize-medium);
  --klik-button-font-size-medium: var(--dt-global-klikui-fontsize-medium);
  --klik-button-font-size-large: var(--dt-global-klikui-fontsize-xl);

  /* radii */
  --klik-border-radius-small: var(--dt-global-klikui-radii-sm);
  --klik-border-radius-medium: var(--dt-global-klikui-radii-base);
  --klik-border-radius-large: var(--dt-global-klikui-radii-medium);
  --klik-border-radius-x-large: var(--dt-global-klikui-radii-large);

  /* input */
  --klik-input-border-width: var(--dt-global-klikui-border-2px);

  --klik-input-height-small: var(--dt-global-klikui-size-input-small);
  --klik-input-height-medium: var(--dt-global-klikui-size-input-medium);
  --klik-input-height-large: var(--dt-global-klikui-size-input-large);

  --klik-input-font-weight-medium: var(--dt-global-klikui-fontweight-medium);

  --klik-input-font-size-small: var(--dt-global-klikui-fontsize-medium);
  --klik-input-font-size-medium: var(--dt-global-klikui-fontsize-lg);
  --klik-input-font-size-large: var(--dt-global-klikui-fontsize-xl);

  --klik-button-icon-size-small: 0.875rem; /* */
  --klik-button-icon-size-medium: 1rem;
  --klik-button-icon-size-large: 1.625rem; /* */
}


/* ------------------- ./src/tokens/css/900-fonts-cerapro.css ----------------------*/
@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: 300;
  src: url('../assets/fonts/cera-pro/CeraPro-Light.eot');
  src: local('Cera Pro Light'), local('CeraPro-Light'),
    url('../assets/fonts/cera-pro/CeraPro-Light.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Light.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Light.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Light.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: 500;
  src: url('../assets/fonts/cera-pro/CeraPro-MediumItalic.eot');
  src: local('Cera Pro Medium Italic'), local('CeraPro-MediumItalic'),
    url('../assets/fonts/cera-pro/CeraPro-MediumItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-MediumItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-MediumItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-MediumItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: normal;
  src: url('../assets/fonts/cera-pro/CeraPro-RegularItalic.eot');
  src: local('Cera Pro Regular Italic'), local('CeraPro-RegularItalic'),
    url('../assets/fonts/cera-pro/CeraPro-RegularItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-RegularItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-RegularItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-RegularItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: 900;
  src: url('../assets/fonts/cera-pro/CeraPro-BlackItalic.eot');
  src: local('Cera Pro Black Italic'), local('CeraPro-BlackItalic'),
    url('../assets/fonts/cera-pro/CeraPro-BlackItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-BlackItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-BlackItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-BlackItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: 500;
  src: url('../assets/fonts/cera-pro/CeraPro-Medium.eot');
  src: local('Cera Pro Medium'), local('CeraPro-Medium'),
    url('../assets/fonts/cera-pro/CeraPro-Medium.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Medium.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Medium.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Medium.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: bold;
  src: url('../assets/fonts/cera-pro/CeraPro-BoldItalic.eot');
  src: local('Cera Pro Bold Italic'), local('CeraPro-BoldItalic'),
    url('../assets/fonts/cera-pro/CeraPro-BoldItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-BoldItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-BoldItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-BoldItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: 100;
  src: url('../assets/fonts/cera-pro/CeraPro-ThinItalic.eot');
  src: local('Cera Pro Thin Italic'), local('CeraPro-ThinItalic'),
    url('../assets/fonts/cera-pro/CeraPro-ThinItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-ThinItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-ThinItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-ThinItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: italic;
  font-weight: 300;
  src: url('../assets/fonts/cera-pro/CeraPro-LightItalic.eot');
  src: local('Cera Pro Light Italic'), local('CeraPro-LightItalic'),
    url('../assets/fonts/cera-pro/CeraPro-LightItalic.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-LightItalic.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-LightItalic.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-LightItalic.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: 900;
  src: url('../assets/fonts/cera-pro/CeraPro-Black.eot');
  src: local('Cera Pro Black'), local('CeraPro-Black'),
    url('../assets/fonts/cera-pro/CeraPro-Black.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Black.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Black.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Black.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: bold;
  src: url('../assets/fonts/cera-pro/CeraPro-Bold.eot');
  src: local('Cera Pro Bold'), local('CeraPro-Bold'),
    url('../assets/fonts/cera-pro/CeraPro-Bold.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Bold.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Bold.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Bold.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: normal;
  src: url('../assets/fonts/cera-pro/CeraPro-Regular.eot');
  src: local('Cera Pro Regular'), local('CeraPro-Regular'),
    url('../assets/fonts/cera-pro/CeraPro-Regular.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Regular.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Regular.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Regular.ttf') format('truetype');
}

@font-face {
  font-family: 'Cera Pro';
  font-style: normal;
  font-weight: 100;
  src: url('../assets/fonts/cera-pro/CeraPro-Thin.eot');
  src: local('Cera Pro Thin'), local('CeraPro-Thin'),
    url('../assets/fonts/cera-pro/CeraPro-Thin.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/cera-pro/CeraPro-Thin.woff2') format('woff2'),
    url('../assets/fonts/cera-pro/CeraPro-Thin.woff') format('woff'),
    url('../assets/fonts/cera-pro/CeraPro-Thin.ttf') format('truetype');
}
`;
  