// autogenerated by src/tokens/klik2sl.js
import { css } from 'lit';

export default css`
  :root {
    /*
 * Global DT Color Primitives
 */

    /* slate */
    --dt-global-klik-color-slate-10: 252 252 252;
    --dt-global-klik-color-slate-30: 248 248 248;
    --dt-global-klik-color-slate-50: 241 241 241;
    --dt-global-klik-color-slate-100: 227 227 225;
    --dt-global-klik-color-slate-200: 207 207 204;
    --dt-global-klik-color-slate-300: 178 178 176;
    --dt-global-klik-color-slate-400: 150 150 148;
    --dt-global-klik-color-slate-500: 118 118 116;
    --dt-global-klik-color-slate-600: 97 97 95;
    --dt-global-klik-color-slate-700: 77 77 75;
    --dt-global-klik-color-slate-800: 59 59 57;
    --dt-global-klik-color-slate-900: 41 41 40;

    /* turquoise */
    --dt-global-klik-color-turquoise-10: 250 253 253;
    --dt-global-klik-color-turquoise-30: 242 251 252;
    --dt-global-klik-color-turquoise-50: 223 242 245;
    --dt-global-klik-color-turquoise-100: 194 236 242;
    --dt-global-klik-color-turquoise-200: 139 220 232;
    --dt-global-klik-color-turquoise-300: 81 196 214;
    --dt-global-klik-color-turquoise-400: 31 163 184;
    --dt-global-klik-color-turquoise-500: 6 130 148;
    --dt-global-klik-color-turquoise-600: 1 105 120;
    --dt-global-klik-color-turquoise-700: 1 82 94;
    --dt-global-klik-color-turquoise-800: 4 63 71;
    --dt-global-klik-color-turquoise-900: 6 45 51;

    /* teal */
    --dt-global-klik-color-teal-10: 250 252 252;
    --dt-global-klik-color-teal-30: 245 249 250;
    --dt-global-klik-color-teal-50: 233 242 245;
    --dt-global-klik-color-teal-100: 211 231 237;
    --dt-global-klik-color-teal-200: 177 211 222;
    --dt-global-klik-color-teal-300: 141 186 201;
    --dt-global-klik-color-teal-400: 97 152 171;
    --dt-global-klik-color-teal-500: 70 123 140;
    --dt-global-klik-color-teal-600: 55 104 120;
    --dt-global-klik-color-teal-700: 41 79 92;
    --dt-global-klik-color-teal-800: 32 60 69;
    --dt-global-klik-color-teal-900: 21 36 41;

    /* light-blue */
    --dt-global-klik-color-light-blue-10: 249 251 252;
    --dt-global-klik-color-light-blue-30: 245 248 250;
    --dt-global-klik-color-light-blue-50: 232 242 250;
    --dt-global-klik-color-light-blue-100: 202 229 250;
    --dt-global-klik-color-light-blue-200: 166 211 247;
    --dt-global-klik-color-light-blue-300: 121 188 242;
    --dt-global-klik-color-light-blue-400: 69 153 222;
    --dt-global-klik-color-light-blue-500: 36 123 191;
    --dt-global-klik-color-light-blue-600: 23 102 166;
    --dt-global-klik-color-light-blue-700: 15 83 138;
    --dt-global-klik-color-light-blue-800: 12 65 107;
    --dt-global-klik-color-light-blue-900: 10 44 71;

    /* dark-blue */
    --dt-global-klik-color-dark-blue-10: 250 251 252;
    --dt-global-klik-color-dark-blue-30: 242 246 252;
    --dt-global-klik-color-dark-blue-50: 232 240 252;
    --dt-global-klik-color-dark-blue-100: 210 225 252;
    --dt-global-klik-color-dark-blue-200: 177 204 250;
    --dt-global-klik-color-dark-blue-300: 138 177 242;
    --dt-global-klik-color-dark-blue-400: 95 145 232;
    --dt-global-klik-color-dark-blue-500: 52 110 209;
    --dt-global-klik-color-dark-blue-600: 25 81 178;
    --dt-global-klik-color-dark-blue-700: 12 57 135;
    --dt-global-klik-color-dark-blue-800: 11 47 110;
    --dt-global-klik-color-dark-blue-900: 11 37 82;

    /* purple */
    --dt-global-klik-color-purple-10: 251 250 252;
    --dt-global-klik-color-purple-30: 248 245 252;
    --dt-global-klik-color-purple-50: 243 237 252;
    --dt-global-klik-color-purple-100: 232 220 250;
    --dt-global-klik-color-purple-200: 212 191 245;
    --dt-global-klik-color-purple-300: 191 162 235;
    --dt-global-klik-color-purple-400: 162 126 217;
    --dt-global-klik-color-purple-500: 138 98 196;
    --dt-global-klik-color-purple-600: 115 76 173;
    --dt-global-klik-color-purple-700: 91 58 140;
    --dt-global-klik-color-purple-800: 69 43 107;
    --dt-global-klik-color-purple-900: 46 32 66;

    /* magenta */
    --dt-global-klik-color-magenta-10: 252 250 251;
    --dt-global-klik-color-magenta-30: 252 245 248;
    --dt-global-klik-color-magenta-50: 252 235 243;
    --dt-global-klik-color-magenta-100: 252 212 231;
    --dt-global-klik-color-magenta-200: 250 182 214;
    --dt-global-klik-color-magenta-300: 242 148 192;
    --dt-global-klik-color-magenta-400: 229 103 162;
    --dt-global-klik-color-magenta-500: 207 62 129;
    --dt-global-klik-color-magenta-600: 178 37 103;
    --dt-global-klik-color-magenta-700: 140 22 77;
    --dt-global-klik-color-magenta-800: 97 19 56;
    --dt-global-klik-color-magenta-900: 64 22 42;

    /* copper */
    --dt-global-klik-color-copper-10: 255 253 250;
    --dt-global-klik-color-copper-30: 252 247 240;
    --dt-global-klik-color-copper-50: 250 239 225;
    --dt-global-klik-color-copper-100: 251 220 183;
    --dt-global-klik-color-copper-200: 243 196 139;
    --dt-global-klik-color-copper-300: 227 166 91;
    --dt-global-klik-color-copper-400: 204 138 55;
    --dt-global-klik-color-copper-500: 163 104 31;
    --dt-global-klik-color-copper-600: 133 83 21;
    --dt-global-klik-color-copper-700: 101 65 19;
    --dt-global-klik-color-copper-800: 74 50 20;
    --dt-global-klik-color-copper-900: 51 37 20;

    /* information */
    --dt-global-klik-color-information-50: 230 245 252;
    --dt-global-klik-color-information-100: 197 234 252;
    --dt-global-klik-color-information-400: 23 159 227;
    --dt-global-klik-color-information-500: 0 124 186;
    --dt-global-klik-color-information-600: 5 104 153;

    /* success */
    --dt-global-klik-color-success-50: 232 247 230;
    --dt-global-klik-color-success-100: 211 247 208;
    --dt-global-klik-color-success-400: 28 178 12;
    --dt-global-klik-color-success-500: 16 138 6;
    --dt-global-klik-color-success-600: 17 110 9;

    /* warning */
    --dt-global-klik-color-warning-50: 252 242 219;
    --dt-global-klik-color-warning-100: 252 233 192;
    --dt-global-klik-color-warning-400: 242 167 5;
    --dt-global-klik-color-warning-500: 158 108 0;
    --dt-global-klik-color-warning-600: 128 87 0;

    /* error */
    --dt-global-klik-color-error-50: 255 242 242;
    --dt-global-klik-color-error-100: 255 222 222;
    --dt-global-klik-color-error-400: 245 91 91;
    --dt-global-klik-color-error-500: 219 31 31;
    --dt-global-klik-color-error-600: 178 7 7;

    --dt-global-klik-color-black: 10 10 10;
    --dt-global-klik-color-white: 255 255 255;
  }
`;
